### ISSUE TITLE
migrating the plugin to the V2 embedding

### ISSUE THREAD

**Issue by ArivhaySoft** [vavadiyahiren/xmpp_plugin#1]
The plugin `xmpp_plugin` uses a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise, consider removing it since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.

any solution for this

**Comment by vavadiyahiren** [comment]
I am about to new release today with the migration @ArivhaySoft 

Hope that resolves your problem

**Comment by vavadiyahiren** [comment]
Try with v1.1.13

**Comment by ArivhaySoft** [comment]
I am very grateful for the solution
