### ISSUE TITLE
Presence change issue

### ISSUE THREAD

**Issue by SergeiKovaliov** [vavadiyahiren/xmpp_plugin#101]
After moving from version 2.2.3 to 2.2.9, I started getting an error related to the presence change. My program cannot correctly handle the onPresenceChange method of the DataChangeEvents interface because your plugin throws an error casting a String to PresentMode in the present_mode.dart class on line 15. Since the presenceMode and presenceType fields were previously of type String, this problem did not arise. Should I do the casting manually or can you fix this?

**Comment by harmispatel** [comment]
I am also facing same issu

**Comment by vavadiyahiren** [comment]
@harmispatel @SergeiKovaliov noted, Will get it fixed by Jan 28th.
