### ISSUE TITLE
Troubleshooting TLS Connectivity Issues with ejabberd on Ubuntu Focal

### ISSUE THREAD

**Issue by LumiProj** [vavadiyahiren/xmpp_plugin#103]
I am using ejabberd on Ubuntu Focal, where I have configured the server to use port 5222 and StartTLS. However, I am encountering connectivity issues with the server when using the following code snippet:

final param = {
  "user_jid": "guest@sip.abc.live",
  "password": "computer",
  "host": "sip.abc.live",
  "port": "5222",
  "nativeLogFilePath": "filepath",
  "requireSSLConnection": true,
  "autoDeliveryReceipt": false,
  "useStreamManagement": false,
  "automaticReconnection": true,
};

xmppConnection = XmppConnection(param);

await xmppConnection?.start(_onError);
await xmppConnection?.login();

The connection only succeeds when I set the server setting StartTLS to false. Can you please guide me on why this plugin does not seem to support TLS connections?

**Comment by vavadiyahiren** [comment]
@LumiProj  It does support the TLS connection.

Did you have self-signed certificate assigned to TLS , If so it might create problem with the current implementations.

**Comment by LumiProj** [comment]
Hi, Sorry for late replay I am using godady but now it is working now. Thanks
