### ISSUE TITLE
Error when get or send base64 data

### ISSUE THREAD

**Issue by mehmetgencdal** [vavadiyahiren/xmpp_plugin#108]
When i send or get base64 data:

`W/BpBinder(24847): Large outgoing transaction of 768240 bytes, interface descriptor , code 22`

When data size is not large there is not a problem.

**Comment by mehmetgencdal** [comment]
@vavadiyahiren @dr7866 @therif

**Comment by dr7866** [comment]
@mehmetgencdal what You Are Trying To Do ???

**Comment by dr7866** [comment]
@mehmetgencdal basically right now there no implementation of file transfer in it 
i have another solution of this 
you have to use third party server to upload your file then send a link of uploaded file to your friend

**Comment by mehmetgencdal** [comment]
> @mehmetgencdal basically right now there no implementation of file transfer in it 
> i have another solution of this 
> you have to use third party server to upload your file then send a link of uploaded file to your friend 

@dr7866 thanks for the answer. I have another question about something else. I'm going to ask in another issue whenever I'm available. If you reply I'll be happy
