### ISSUE TITLE
Connecting to OpenFire without username and password

### ISSUE THREAD

**Issue by aysesenses** [vavadiyahiren/xmpp_plugin#116]
The only information I have to connect to the server is host, service name, domain and port information. After connecting to the server, it creates a user in Openfire and provides me with a user ID and password. Can I connect this way? @florisgravendeel @therif @vavadiyahiren @Kabariya @umairrafiq1133

**Comment by vavadiyahiren** [comment]
You may install openfire-Rest api plugin where you can register your user prior to login here. @aysesenses
