### ISSUE TITLE
No support for Android 14 (API 34).

### ISSUE THREAD

**Issue by elenaapp** [vavadiyahiren/xmpp_plugin#124]
Hello, 
could you please fix this problem? 
Maybe you can  try the Pull Request from kamil-kmetyk
Thank you in advance.

**Comment by vavadiyahiren** [comment]
Will try merge it this week.

**Comment by vavadiyahiren** [comment]
PR Has been closed.

**Comment by elenaapp** [comment]
Thank you :-)
