### ISSUE TITLE
MAM function doesn't return anything

### ISSUE THREAD

**Issue by robertscally** [vavadiyahiren/xmpp_plugin#14]
Hi,

Thank you for your work on this plugin.

The flutterXmpp.requestMamMessages(userJid, requestSince, requestBefore, limit) function does not return any messages. Is that correct? How do I receive the archived messages?

```
  Future<void> requestMamMessages(
      String userJid, String requestSince, String requestBefore, String limit) async {
    print(
        " Plugin : User Jid : $userJid , Request since : $requestSince , Request Before : $requestBefore, Limit : $limit ");
    final params = {
      "userJid": userJid,
      "requestBefore": requestBefore,
      "requestSince": requestSince,
      "limit": limit
    };
    await _channel.invokeMethod('request_mam', params);
  }
```

Thanks,
Robert

**Comment by vavadiyahiren** [comment]
You should expect the message that on the receivemessage listener. @robertscally 

let me know if that doesn’t work.
