### ISSUE TITLE
error when connecting to server after some minutes of inactivity. Any way to resolve?

### ISSUE THREAD

**Issue by mugambikimathi** [vavadiyahiren/xmpp_plugin#15]
I/XMPPTCPConnection(13769): Exception while waiting for closing stream element from the server XMPPTCPConnection[demo2@domain.com/resource] (0)
I/XMPPTCPConnection(13769): org.jivesoftware.smack.SmackException$NoResponseException: No response received within reply timeout. Timeout was 5000ms (~5s). While waiting for stream closing element received
I/XMPPTCPConnection(13769): 	at org.jivesoftware.smack.SynchronizationPoint.checkForResponse(SynchronizationPoint.java:317)
I/XMPPTCPConnection(13769): 	at org.jivesoftware.smack.SynchronizationPoint.checkIfSuccessOrWait(SynchronizationPoint.java:160)
I/XMPPTCPConnection(13769): 	at org.jivesoftware.smack.tcp.XMPPTCPConnection.shutdown(XMPPTCPConnection.java:524)
I/XMPPTCPConnection(13769): 	at org.jivesoftware.smack.tcp.XMPPTCPConnection.shutdown(XMPPTCPConnection.java:503)
I/XMPPTCPConnection(13769): 	at org.jivesoftware.smack.AbstractXMPPConnection.disconnect(AbstractXMPPConnection.java:789)
I/XMPPTCPConnection(13769): 	at org.jivesoftware.smack.AbstractXMPPConnection.disconnect(AbstractXMPPConnection.java:761)
I/XMPPTCPConnection(13769): 	at org.xrstudio.xmpp.flutter_xmpp.Connection.FlutterXmppConnection.disconnect(FlutterXmppConnection.java:624)
I/XMPPTCPConnection(13769): 	at org.xrstudio.xmpp.flutter_xmpp.Connection.FlutterXmppConnectionService$2.run(FlutterXmppConnectionService.java:114)
I/XMPPTCPConnection(13769): 	at android.os.Handler.handleCallback(Handler.java:938)
I/XMPPTCPConnection(13769): 	at android.os.Handler.dispatchMessage(Handler.java:99)
I/XMPPTCPConnection(13769): 	at android.os.Looper.loop(Looper.java:223)
I/XMPPTCPConnection(13769): 	at org.xrstudio.xmpp.flutter_xmpp.Connection.FlutterXmppConnectionService$1.run(FlutterXmppConnectionService.java:95)
I/XMPPTCPConnection(13769): 	at java.lang.Thread.run(Thread.java:923)
D/flutter_xmpp(13769):  ConnectionClosed(): 
D/SMACK   (13769): XMPPConnection closed (XMPPTCPConnection[demo2@domain.com/resource] (0))
D/TAG     (13769):  RECEIVE_MESSAGE-->> {chatStateType=, customText=null, from=Disconnected, senderJid=, id=Disconnected, time=0, type=null, body=Disconnected, msgtype=Disconnected}

**Comment by vavadiyahiren** [comment]
Looking at the logs it looks like you lost the connection ? 

- Any pattern or use cases how it does happen with you ? @mugambikimathi

**Comment by adilexperience** [comment]
This issue is still rising after a few minutes of inactivity.
