### ISSUE TITLE
Runtime Error xmlpullparser

### ISSUE THREAD

**Issue by mugambikimathi** [vavadiyahiren/xmpp_plugin#19]
I get the below Error when i try to login using release version. The error does not appear during debug.  Any pointers how to resolve. 
`E/AndroidRuntime(22968): java.lang.ExceptionInInitializerError
E/AndroidRuntime(22968):        at l.b.a.m.i(Unknown Source:0)
E/AndroidRuntime(22968):        at l.b.a.d.<clinit>(Unknown Source:0)
E/AndroidRuntime(22968):        at l.b.a.k0.d.y(Unknown Source:0)
E/AndroidRuntime(22968):        at org.xrstudio.xmpp.flutter_xmpp.Connection.a.f(Unknown Source:4)
E/AndroidRuntime(22968):        at org.xrstudio.xmpp.flutter_xmpp.Connection.FlutterXmppConnectionService.e(Unknown Source:36)
E/AndroidRuntime(22968):        at org.xrstudio.xmpp.flutter_xmpp.Connection.FlutterXmppConnectionService.b(Unknown Source:0)
E/AndroidRuntime(22968):        at org.xrstudio.xmpp.flutter_xmpp.Connection.FlutterXmppConnectionService$a.run(Unknown Source:15)
E/AndroidRuntime(22968):        at java.lang.Thread.run(Thread.java:784)
E/AndroidRuntime(22968): Caused by: java.lang.IllegalStateException: Could not parse Smack configuration file
E/AndroidRuntime(22968):        at l.b.a.p.<clinit>(Unknown Source:197)
E/AndroidRuntime(22968):        ... 8 more
E/AndroidRuntime(22968): Caused by: org.xmlpull.v1.a: caused by: org.xmlpull.v1.a: resource not found: /META-INF/services/org.xmlpull.v1.XmlPullParserFactory make sure that parser implementing XmlPull API is available
E/AndroidRuntime(22968):        at org.xmlpull.v1.b.b(Unknown Source:214)
E/AndroidRuntime(22968):        at org.xmlpull.v1.b.a(Unknown Source:1)
E/AndroidRuntime(22968):        at l.b.a.p.d(Unknown Source:0)
E/AndroidRuntime(22968):        at l.b.a.p.c(Unknown Source:6)
E/AndroidRuntime(22968):        at l.b.a.p.<clinit>(Unknown Source:98)
E/AndroidRuntime(22968):        ... 8 more
`

**Comment by vavadiyahiren** [comment]
You need to add the proguard rules while releasing for android or either disable the minify. @mugambikimathi
