### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by ThawSoe** [vavadiyahiren/xmpp_plugin#20]
![image](https://user-images.githubusercontent.com/52695650/170419778-566085dc-5e1b-47a4-9f2e-2837a2a2c51a.png)

I got only this error while connecting to server.
This is why ?

**Comment by milkyway044** [comment]
+1 `[log] onConnectionEvents ~~>>{type: XmppConnectionState.disconnected, error: }`

**Comment by vavadiyahiren** [comment]
@ThawSoe These seems your xmpp server drops the connection, Can you please enabled the logs for xmpp plugin and send full log here ?

**Comment by vavadiyahiren** [comment]
Closed due to inactivity, Reopen if anyone facing the same problem
