### ISSUE TITLE
on IOS get_my_rosters after login and then logout and then login return empty list

### ISSUE THREAD

**Issue by dkramorov** [vavadiyahiren/xmpp_plugin#21]
ios only, android receive roster on this scenario correctly
1) Login
2) get Roster - receive full roster will return correct result
3) logout
4) login
5) get Roster return empty list

**Comment by vavadiyahiren** [comment]
Can you please share debug logs here and i can help ? @dkramorov

**Comment by vavadiyahiren** [comment]
Closed due to inactivity

**Comment by sana2024** [comment]
hey, i have the same problem, plus on ios when i login and getRosters the list is empty, but when i refresh it, it gets all the rosters!!!!
