### ISSUE TITLE
can not catch auth error when credentials are incorrect

### ISSUE THREAD

**Issue by dkramorov** [vavadiyahiren/xmpp_plugin#22]
android:
i try enter incorrect login/password pair and receive events Connected, then smack error, then Disconnected
I can't catch credentials error on app layer, 
for example, on ios i receive Failed event, but not on android

**Comment by vavadiyahiren** [comment]
WIll be added soon @dkramorov

**Comment by vavadiyahiren** [comment]
@dkramorov Fixed.
