### ISSUE TITLE
MAM Messages request ordering is wrong

### ISSUE THREAD

**Issue by AndonZeno** [vavadiyahiren/xmpp_plugin#27]
Hello when you do a MAM messaging request, the order of retrieved messages should be newest first. Right now its oldest first so onChatMessage captures oldes events first. 
Can ordering be fixed?

**Comment by vavadiyahiren** [comment]
Do you test on android  or ios ? 

Which server do you use for backend ? @AndonZeno

**Comment by AndonZeno** [comment]
Currently testing on Android. ejabberd @vavadiyahiren

**Comment by AndonZeno** [comment]
Is there any workaround for this @vavadiyahiren ? Or maybe you adding support to query messages by id?

**Comment by vavadiyahiren** [comment]
query message by id can work for the android but not for ios, And it should work in liner way for android as always, 

Would you like to share your logs for the mam query ?

**Comment by AndonZeno** [comment]
@vavadiyahiren  The order is reversed. Means, onChatMessage is capturing messages ordered time ascending. It should be time descending. For pagination purposes we need to catch latest messages first and then on scroll to load earliest ones.
Check below a copy of logs

**Comment by AndonZeno** [comment]
[log] onChatMessage: {customText: , from: ruartemisa@testsrv/converse.js-111983666, senderJid: ruartemisa@testsrv/converse.js-111983666, time: 1658224805324, id: 4da49bb0-a92e-4e4d-bb4b-33cc3017825c, type: chatstate, body: 10, msgtype: chat, bubbleType: , mediaURL: , isReadSent: 0}
D/TAG     ( 5929):  RECEIVE_MESSAGE-->> {chatStateType=, customText=, from=andon@testsrv, senderJid=andon@testsrv, id=null, time=0, type=Message, body=null, msgtype=normal}
[log] onChatMessage: {customText: , from: ruartemisa@testsrv/converse.js-111983666, senderJid: ruartemisa@testsrv/converse.js-111983666, time: 1658224805324, id: 4da49bb0-a92e-4e4d-bb4b-33cc3017825c, type: chatstate, body: 10, msgtype: chat, bubbleType: , mediaURL: , isReadSent: 0}
D/TAG     ( 5929):  RECEIVE_MESSAGE-->> {chatStateType=, customText=, from=andon@testsrv, senderJid=andon@testsrv, id=null, time=0, type=Message, body=null, msgtype=normal}
[log] onChatMessage: {customText: , from: ruartemisa@testsrv/converse.js-111983666, senderJid: ruartemisa@testsrv/converse.js-111983666, time: 1658224805324, id: 4da49bb0-a92e-4e4d-bb4b-33cc3017825c, type: chatstate, body: 10, msgtype: chat, bubbleType: , mediaURL: , isReadSent: 0}
[log] onChatMessage: {customText: , from: andon@testsrv/Android, senderJid: andon@testsrv/Android, time: 1658224839633, id: 1658224839633, type: Message, body: 11, msgtype: chat, bubbleType: , mediaURL: , isReadSent: 0}
D/TAG     ( 5929):  RECEIVE_MESSAGE-->> {chatStateType=, customText=, from=andon@testsrv, senderJid=andon@testsrv, id=null, time=0, type=Message, body=null, msgtype=normal}
[log] onChatMessage: {customText: , from: andon@testsrv/Android, senderJid: andon@testsrv/Android, time: 1658224839633, id: 1658224839633, type: Message, body: 11, msgtype: chat, bubbleType: , mediaURL: , isReadSent: 0}
D/EGL_emulation( 5929): app_time_stats: avg=110.12ms min=11.22ms max=640.64ms count=9
[log] onChatMessage: {customText: , from: andon@testsrv/Android, senderJid: andon@testsrv/Android, time: 1658224839633, id: 1658224839633, type: Message, body: 11, msgtype: chat, bubbleType: , mediaURL: , isReadSent: 0}
D/TAG     ( 5929):  RECEIVE_MESSAGE-->> {chatStateType=, customText=, from=andon@testsrv, senderJid=andon@testsrv, id=null, time=0, type=Message, body=null, msgtype=normal}
3
[log] onChatMessage: {customText: , from: ruartemisa@testsrv/converse.js-111983666, senderJid: ruartemisa@testsrv/converse.js-111983666, time: 0, id: 1658224839633, type: Delivery-Ack, body: , msgtype: chat, bubbleType: , mediaURL: , isReadSent: 0}
D/TAG     ( 5929):  RECEIVE_MESSAGE-->> {chatStateType=, customText=, from=andon@testsrv, senderJid=andon@testsrv, id=null, time=0, type=Message, body=null, msgtype=normal}
2
[log] onChatMessage: {customText: , from: andon@testsrv/Android, senderJid: andon@testsrv/Android, time: 1658231696679, id: 1658231696679, type: Message, body: 12, msgtype: chat, bubbleType: , mediaURL: , isReadSent: 0}
D/TAG     ( 5929):  RECEIVE_MESSAGE-->> {chatStateType=, customText=, from=andon@testsrv, senderJid=andon@testsrv, id=null, time=0, type=Message, body=null, msgtype=normal}
[log] onChatMessage: {customText: , from: andon@testsrv/Android, senderJid: andon@testsrv/Android, time: 1658231696679, id: 1658231696679, type: Message, body: 12, msgtype: chat, bubbleType: , mediaURL: , isReadSent: 0}
[log] onChatMessage: {customText: , from: andon@testsrv/Android, senderJid: andon@testsrv/Android, time: 1658231699453, id: 1658231699453, type: Message, body: 13, msgtype: chat, bubbleType: , mediaURL: , isReadSent: 0}
D/TAG     ( 5929):  RECEIVE_MESSAGE-->> {chatStateType=, customText=, from=andon@testsrv, senderJid=andon@testsrv, id=null, time=0, type=Message, body=null, msgtype=normal}
[log] onChatMessage: {customText: , from: andon@testsrv/Android, senderJid: andon@testsrv/Android, time: 1658231699453, id: 1658231699453, type: Message, body: 13, msgtype: chat, bubbleType: , mediaURL: , isReadSent: 0}
D/TAG     ( 5929):  RECEIVE_MESSAGE-->> {chatStateType=, customText=, from=andon@testsrv, senderJid=andon@testsrv, id=null, time=0, type=Message, body=null, msgtype=normal}
[log] onChatMessage: {customText: , from: andon@testsrv/Android, senderJid: andon@testsrv/Android, time: 1658231699453, id: 1658231699453, type: Message, body: 13, msgtype: chat, bubbleType: , mediaURL: , isReadSent: 0}
[log] onChatMessage: {customText: , from: ruartemisa@testsrv/converse.js-111983666, senderJid: ruartemisa@testsrv/converse.js-111983666, time: 0, id: 1658231696679, type: Delivery-Ack, body: , msgtype: chat, bubbleType: , mediaURL: , isReadSent: 0}
D/TAG     ( 5929):  RECEIVE_MESSAGE-->> {chatStateType=, customText=, from=andon@testsrv, senderJid=andon@testsrv, id=null, time=0, type=Message, body=null, msgtype=normal}
2
[log] onChatMessage: {customText: , from: ruartemisa@testsrv/converse.js-111983666, senderJid: ruartemisa@testsrv/converse.js-111983666, time: 0, id: 1658231696679, type: Delivery-Ack, body: , msgtype: chat, bubbleType: , mediaURL: , isReadSent: 0}
3
[log] onChatMessage: {customText: , from: ruartemisa@testsrv/converse.js-111983666, senderJid: ruartemisa@testsrv/converse.js-111983666, time: 0, id: 1658231699453, type: Delivery-Ack, body: , msgtype: chat, bubbleType: , mediaURL: , isReadSent: 0}
3
[log] onChatMessage: {customText: , from: ruartemisa@testsrv/Android, senderJid: ruartemisa@testsrv/Android, time: 1658232179141, id: 1658232179141, type: Message, body: hi, msgtype: chat, bubbleType: , mediaURL: , isReadSent: 0}
3
[log] onChatMessage: {customText: , from: andon@testsrv/Android, senderJid: andon@testsrv/Android, time: 1658232185264, id: 1658232185264, type: Message, body: hello, msgtype: chat, bubbleType: , mediaURL: , isReadSent: 0}
3
[log] onChatMessage: {customText: , from: ruartemisa@testsrv/Android, senderJid: ruartemisa@testsrv/Android, time: 1658232192001, id: 1658232192001, type: Message, body: :D, msgtype: chat, bubbleType: , mediaURL: , isReadSent: 0}
3
[log] onChatMessage: {customText: , from: andon@testsrv/Android-1658233299181, senderJid: andon@testsrv/Android-1658233299181, time: 1658233322467, id: 1658233322467, type: Message, body: test, msgtype: chat, bubbleType: , mediaURL: , isReadSent: 0}
3
[log] onChatMessage: {customText: , from: ruartemisa@testsrv/converse.js-97202855, senderJid: ruartemisa@testsrv/converse.js-97202855, time: 0, id: 1658233322467, type: Delivery-Ack, body: , msgtype: chat, bubbleType: , mediaURL: , isReadSent: 0}
3
[log] onChatMessage: {customText: , from: andon@testsrv/Android, senderJid: andon@testsrv/Android, time: 1658233354652, id: 1658233354652, type: Message, body: hi, msgtype: chat, bubbleType: , mediaURL: , isReadSent: 0}
3
[log] onChatMessage: {customText: , from: ruartemisa@testsrv/converse.js-97202855, senderJid: ruartemisa@testsrv/converse.js-97202855, time: 0, id: 1658233354652, type: Delivery-Ack, body: , msgtype: chat, bubbleType: , mediaURL: , isReadSent: 0}
3
[log] onChatMessage: {customText: , from: andon@testsrv/Android-1658233299181, senderJid: andon@testsrv/Android-1658233299181, time: 1658233368496, id: 1658233368496, type: Message, body: ?, msgtype: chat, bubbleType: , mediaURL: , isReadSent: 0}
3
[log] onChatMessage: {customText: , from: ruartemisa@testsrv/converse.js-97202855, senderJid: ruartemisa@testsrv/converse.js-97202855, time: 0, id: 1658233368496, type: Delivery-Ack, body: , msgtype: chat, bubbleType: , mediaURL: , isReadSent: 0}
3
[log] onChatMessage: {customText: , from: andon@testsrv/Android, senderJid: andon@testsrv/Android, time: 1658233429406, id: 1658233429406, type: Message, body: yes, msgtype: chat, bubbleType: , mediaURL: , isReadSent: 0}
3
[log] onChatMessage: {customText: , from: ruartemisa@testsrv/converse.js-97202855, senderJid: ruartemisa@testsrv/converse.js-97202855, time: 0, id: 1658233429406, type: Delivery-Ack, body: , msgtype: chat, bubbleType: , mediaURL: , isReadSent: 0}
3
[log] onChatMessage: {customText: , from: andon@testsrv/Android, senderJid: andon@testsrv/Android, time: 1658233447839, id: 1658233447839, type: Message, body: ?, msgtype: chat, bubbleType: , mediaURL: , isReadSent: 0}
3
[log] onChatMessage: {customText: , from: andon@testsrv/Android, senderJid: andon@testsrv/Android, time: 1658233453902, id: 1658233453902, type: Message, body: ?, msgtype: chat, bubbleType: , mediaURL: , isReadSent: 0}
3
[log] onChatMessage: {customText: , from: andon@testsrv/Android, senderJid: andon@testsrv/Android, time: 1658233473441, id: 1658233473441, type: Message, body: hm, msgtype: chat, bubbleType: , mediaURL: , isReadSent: 0}
3
[log] onChatMessage: {customText: , from: andon@testsrv/Android-1658233299181, senderJid: andon@testsrv/Android-1658233299181, time: 1658233479622, id: 1658233479622, type: Message, body: hm, msgtype: chat, bubbleType: , mediaURL: , isReadSent: 0}
3
[log] onChatMessage: {customText: , from: andon@testsrv/Android-1658233299181, senderJid: andon@testsrv/Android-1658233299181, time: 1658233514230, id: 1658233514230, type: Message, body: lol, msgtype: chat, bubbleType: , mediaURL: , isReadSent: 0}
3
[log] onChatMessage: {customText: , from: andon@testsrv/Android, senderJid: andon@testsrv/Android, time: 1658233522199, id: 1658233522199, type: Message, body: h, msgtype: chat, bubbleType: , mediaURL: , isReadSent: 0}
3
[log] onChatMessage: {customText: , from: andon@testsrv/Android-1658247129168, senderJid: andon@testsrv/Android-1658247129168, time: 1658247417024, id: 1658247417024, type: Message, body: test, msgtype: chat, bubbleType: , mediaURL: , isReadSent: 0}
3
[log] onChatMessage: {customText: , from: ruartemisa@testsrv/converse.js-61401120, senderJid: ruartemisa@testsrv/converse.js-61401120, time: 0, id: 1658247417024, type: Delivery-Ack, body: , msgtype: chat, bubbleType: , mediaURL: , isReadSent: 0}
3
[log] onChatMessage: {customText: , from: ruartemisa@testsrv/converse.js-61401120, senderJid: ruartemisa@testsrv/converse.js-61401120, time: 1658247895767, id: 945f94f4-23dc-43d1-892c-dd97cb2739eb, type: chatstate, body: ?, msgtype: chat, bubbleType: , mediaURL: , isReadSent: 0}
3
[log] onChatMessage: {customText: , from: andon@testsrv/Android-1658249620333, senderJid: andon@testsrv/Android-1658249620333, time: 1658250849449, id: 1658250849449, type: Message, body: test, msgtype: chat, bubbleType: , mediaURL: , isReadSent: 0}
3
[log] onChatMessage: {customText: , from: andon@testsrv/Android-1658249620333, senderJid: andon@testsrv/Android-1658249620333, time: 1658250856632, id: 1658250856632, type: Message, body: ?, msgtype: chat, bubbleType: , mediaURL: , isReadSent: 0}
3
[log] onChatMessage: {customText: , from: ruartemisa@testsrv/converse.js-85546177, senderJid: ruartemisa@testsrv/converse.js-85546177, time: 0, id: 1658250849449, type: Delivery-Ack, body: , msgtype: chat, bubbleType: , mediaURL: , isReadSent: 0}
3
[log] onChatMessage: {customText: , from: ruartemisa@testsrv/converse.js-85546177, senderJid: ruartemisa@testsrv/converse.js-85546177, time: 0, id: 1658250856632, type: Delivery-Ack, body: , msgtype: chat, bubbleType: , mediaURL: , isReadSent: 0}
3
[log] onChatMessage: {customText: , from: ruartemisa@testsrv/converse.js-85546177, senderJid: ruartemisa@testsrv/converse.js-85546177, time: 1658313750849, id: a6b0915e-ec8c-4564-91ac-653c5d0ecf4f, type: chatstate, body: ?, msgtype: chat, bubbleType: , mediaURL: , isReadSent: 0}
3
[log] onChatMessage: {customText: , from: andon@testsrv/Android-1658249620333, senderJid: andon@testsrv/Android-1658249620333, time: 1658252529958, id: 1658252529958, type: Message, body: t, msgtype: chat, bubbleType: , mediaURL: , isReadSent: 0}
3
[log] onChatMessage: {customText: , from: ruartemisa@testsrv/converse.js-85546177, senderJid: ruartemisa@testsrv/converse.js-85546177, time: 0, id: 1658252529958, type: Delivery-Ack, body: , msgtype: chat, bubbleType: , mediaURL: , isReadSent: 0}
3
[log] onChatMessage: {customText: , from: andon@testsrv/Android-1658249620333, senderJid: andon@testsrv/Android-1658249620333, time: 1658252559813, id: 1658252559813, type: Message, body: test, msgtype: chat, bubbleType: , mediaURL: , isReadSent: 0}
3
[log] onChatMessage: {customText: , from: ruartemisa@testsrv/converse.js-85546177, senderJid: ruartemisa@testsrv/converse.js-85546177, time: 0, id: 1658252559813, type: Delivery-Ack, body: , msgtype: chat, bubbleType: , mediaURL: , isReadSent: 0}
3
[log] onChatMessage: {customText: , from: ruartemisa@testsrv/converse.js-85546177, senderJid: ruartemisa@testsrv/converse.js-85546177, time: 1658318265760, id: 740acb29-0386-41ac-b6e8-76cde3f55013, type: chatstate, body: ?, msgtype: chat, bubbleType: , mediaURL: , isReadSent: 0}
3
[log] onChatMessage: {customText: , from: ruartemisa@testsrv/converse.js-85546177, senderJid: ruartemisa@testsrv/converse.js-85546177, time: 1658318866264, id: bbb7266a-a7a3-42bf-9198-48f6c1c5b565, type: chatstate, body: ?, msgtype: chat, bubbleType: , mediaURL: , isReadSent: 0}
3
[log] onChatMessage: {customText: , from: andon@testsrv/Android-1658249620333, senderJid: andon@testsrv/Android-1658249620333, time: 1658256263756, id: 1658256263756, type: Message, body: gj, msgtype: chat, bubbleType: , mediaURL: , isReadSent: 0}
3
[log] onChatMessage: {customText: , from: ruartemisa@testsrv/converse.js-85546177, senderJid: ruartemisa@testsrv/converse.js-85546177, time: 0, id: 1658256263756, type: Delivery-Ack, body: , msgtype: chat, bubbleType: , mediaURL: , isReadSent: 0}
3
[log] onChatMessage: {customText: , from: andon@testsrv/Android-1658249620333, senderJid: andon@testsrv/Android-1658249620333, time: 1658257495980, id: 1658257495980, type: Message, body: test, msgtype: chat, bubbleType: , mediaURL: , isReadSent: 0}
3
[log] onChatMessage: {customText: , from: ruartemisa@testsrv/converse.js-85546177, senderJid: ruartemisa@testsrv/converse.js-85546177, time: 0, id: 1658257495980, type: Delivery-Ack, body: , msgtype: chat, bubbleType: , mediaURL: , isReadSent: 0}

**Comment by AndonZeno** [comment]
Up @vavadiyahiren

**Comment by AndonZeno** [comment]
Any update @vavadiyahiren  ?

**Comment by vavadiyahiren** [comment]
Sorry for being delayed here, Will update the behaviour by next week @AndonZeno

**Comment by AndonZeno** [comment]
Do we have any update here?  @vavadiyahiren
