### ISSUE TITLE
Getting error on running example

### ISSUE THREAD

**Issue by reddnavneet** [vavadiyahiren/xmpp_plugin#28]
Error: Member not found: 'UnicodeChar'.
../…/src/structs.g.dart:554
  int get UnicodeChar => Char.UnicodeChar;
                              ^^^^^^^^^^^
: Error: Setter not found: 'UnicodeChar'.
../…/src/structs.g.dart:555

  set UnicodeChar(int value) => Char.UnicodeChar = value;
                                     ^^^^^^^^^^^
: Error: Member not found: 'AsciiChar'.
../…/src/structs.g.dart:557

  int get AsciiChar => Char.AsciiChar;
                            ^^^^^^^^^
: Error: Setter not found: 'AsciiChar'.
../…/src/structs.g.dart:558
  set AsciiChar(int value) => Char.AsciiChar = value;
                                   ^^^^^^^^^

**Comment by vavadiyahiren** [comment]
Can you once do pub get and try again ? 

Feel free to reopen the issue is still persisted, @reddnavneet
