### ISSUE TITLE
AssertionError on DiscoverInfoProvider.java

### ISSUE THREAD

**Issue by ValerioBarbanti** [vavadiyahiren/xmpp_plugin#30]
Hi! I'm trying to have it run on a project, but I'm having this weird issue where it crashes (closing the app) after connecting.
It is actually working until it crashes, and I can't understand why.

This is what happens:
E/AndroidRuntime(13757): FATAL EXCEPTION: Smack Reader (2)
E/AndroidRuntime(13757): Process: com.example.navis_refit_app, PID: 13757
E/AndroidRuntime(13757): java.lang.AssertionError
E/AndroidRuntime(13757): 	at org.jivesoftware.smackx.disco.provider.DiscoverInfoProvider.parse(DiscoverInfoProvider.java:79)
E/AndroidRuntime(13757): 	at org.jivesoftware.smackx.disco.provider.DiscoverInfoProvider.parse(DiscoverInfoProvider.java:32)
E/AndroidRuntime(13757): 	at org.jivesoftware.smack.provider.Provider.parse(Provider.java:43)
E/AndroidRuntime(13757): 	at org.jivesoftware.smack.util.PacketParserUtils.parseIQ(PacketParserUtils.java:616)
E/AndroidRuntime(13757): 	at org.jivesoftware.smack.util.PacketParserUtils.parseStanza(PacketParserUtils.java:157)
E/AndroidRuntime(13757): 	at org.jivesoftware.smack.AbstractXMPPConnection.parseAndProcessStanza(AbstractXMPPConnection.java:1084)
E/AndroidRuntime(13757): 	at org.jivesoftware.smack.tcp.XMPPTCPConnection.access$1300(XMPPTCPConnection.java:155)
E/AndroidRuntime(13757): 	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:1144)
E/AndroidRuntime(13757): 	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$1000(XMPPTCPConnection.java:1092)
E/AndroidRuntime(13757): 	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:1112)
E/AndroidRuntime(13757): 	at java.lang.Thread.run(Thread.java:923)

I can provide more infos if needed, but as a matter of fact I do have a connection to the XMPP server and I can see the stream starting.

Thanks for your help!

**Comment by vavadiyahiren** [comment]
Seems like DNS problem, Can you share the server details here to check, I can see the port is wrong i guess can you make that correct and try again ? @ValerioBarbanti

**Comment by parisa7103** [comment]
@ValerioBarbanti I have the same problem when running the example part, this is the configuration:

`D/SMACK   (11429): SENT (0): <stream:stream xmlns='jabber:client' to='tribune.app' xmlns:stream='http://etherx.jabber.org/streams' version='1.0' from='admin@tribune.app' xml:lang='en'>
D/SMACK   (11429): RECV (0): <?xml version='1.0' encoding='UTF-8'?><stream:stream xmlns:stream="http://etherx.jabber.org/streams" xmlns="jabber:client" from="10.21.57.78" id="26rg1uy7u4" xml:lang="en" version="1.0">
E/AndroidRuntime(11429): FATAL EXCEPTION: Smack Reader (0)
E/AndroidRuntime(11429): Process: app.tribune.tribune_chat, PID: 11429
E/AndroidRuntime(11429): java.lang.AssertionError
E/AndroidRuntime(11429): 	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:1154)
E/AndroidRuntime(11429): 	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$1000(XMPPTCPConnection.java:1092)
E/AndroidRuntime(11429): 	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:1112)
E/AndroidRuntime(11429): 	at java.lang.Thread.run(Thread.java:764)
[log] didChangeAppLifecycleState()
[log] detachedCallBack()
I/Process (11429): Sending signal. PID: 11429 SIG: 9`

**Comment by Uvais-Mohammad** [comment]
I am also facing the same issue. If there is any updates, please let me know. Thanks in advance 🥰

**Comment by vavadiyahiren** [comment]
Fixed.
