### ISSUE TITLE
is it possible to send a message with an image or other binary file?

### ISSUE THREAD

**Issue by arisAlexis** [vavadiyahiren/xmpp_plugin#34]

**Comment by AndonZeno** [comment]
From what I have checked currently it's not. However you can upload files in your server and use any other flutter package to show the embed the content from the file url.

**Comment by vavadiyahiren** [comment]
That is correct @AndonZeno 

We are not supporting the file transfer yet @arisAlexis

**Comment by arisAlexis** [comment]
Thanks. Then I should send a custom XML payload including the URL ? With
which function is best?

**Comment by AndonZeno** [comment]
@arisAlexis Just send the url as message body.

**Comment by pickgocom** [comment]
is there any plan to support file upload functionality
