### ISSUE TITLE
Logout error on iOS

### ISSUE THREAD

**Issue by AndonZeno** [vavadiyahiren/xmpp_plugin#36]
Hello,
We are encountering an issue when disconnecting xmpp connection. Issue occurs only on iOS not Android.
Check logs:

Time: 2022-09-20 11:07:51.9760
Action: methodReceiveFromFlutter
NativeMethod: logout
Content: nil

addLogger(::) | Not initialize XMPPLogger
 handle(:result:) |vMethod logout
performLogoutActivity(:_:) | logout | arguments: [:]
notiObsXMPPConnectionStatus(notfication:) | XMPPConnetion status Disconnect
xmppStream(:didSend:) | XMPPPresence | presence: <presence type="unavailable"></presence>
notiObsXMPPConnectionStatus(notfication:) | XMPPConnetion status Disconnect
xmppStream(:didFailToSend:error:) | XMPPPresence | presence: <presence type="unavailable"></presence> | error: Error Domain=XMPPStreamErrorDomain Code=1 "(null)"

**Comment by vavadiyahiren** [comment]
@AndonZeno Thanks for the report,Let me investigate the problem.

**Comment by vavadiyahiren** [comment]
@AndonZeno Ios work fine with the latest version now. Please reopen if it is still happening with you.
