### ISSUE TITLE
crashes at login() on Android

### ISSUE THREAD

**Issue by woolfman007** [vavadiyahiren/xmpp_plugin#37]
In debug mode, it works fine; however, in release mode, it crashes the app as soon as I call login(). Like said, everything works in debug mode, (the server credentials are correct and devices can successfully chat in real time).

The crash I get is this Java exception: 

java.lang.RuntimeException: Unable to start service org.xrstudio.xmpp.flutter_xmpp.Connection.FlutterXmppConnectionService@e8f22aa with null: java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Bundle android.content.Intent.getExtras()' on a null object reference

**Comment by woolfman007** [comment]
...btw, I can reproduce this on the official example, too; as soon as I click on connect, the app crashes in release mode but not in debug, where it successfully connects and authorizes

**Comment by vavadiyahiren** [comment]
@woolfman007 Thanks for drawing my attention, I will take a look at this. Which version do you use of the plugin can you please confirm once ?

**Comment by woolfman007** [comment]
Thanks for responding so quickly, I appreciate that very much!

I am using xmpp_plugin: ^2.2.3 in my own project, but I could reproduce that
also in the official example, which I downloaded from GitHub... I'm using
pretty much the latest Flutter version:

Flutter 3.3.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision e3c29ec00c (12 days ago) • 2022-09-14 08:46:55 -0500
Engine • revision a4ff2c53d8
Tools • Dart 2.18.1 • DevTools 2.15.0

**Comment by woolfman007** [comment]
@vavadiyahiren could you already investigate this? Can you reproduce it?

**Comment by vavadiyahiren** [comment]
Fixed with the latest version @woolfman007 , Feel free to reopen this if it is still happening with you.
