### ISSUE TITLE
SSL/TLS required

### ISSUE THREAD

**Issue by gnusagit** [vavadiyahiren/xmpp_plugin#4]
My XMPP server is required to use SSL/TLS configuration. how do I configure xmpp_plugin to be ready for my server.

this my console:
```
I/System.out(22306): [socket]:check permission begin!
D/flutter_xmpp(22306):  Something went wrong while connecting ,make sure the credentials are right and try again: 
W/System.err(22306): org.jivesoftware.smack.SmackException$SecurityRequiredByServerException: SSL/TLS required by server but disabled in client
```

thank you,
Best Regards.

**Comment by sid9890** [comment]
I am also facing same issue i tried lot of stuff yet no luck, my same server is working with XMPP jabber client app,its responding but when I try with the given code here adding proper credentials I get an error-

W/System.err(26207): org.jivesoftware.smack.SmackException$SecurityRequiredByServerException: SSL/TLS required by server but disabled in client

**Comment by vavadiyahiren** [comment]
@gnusagit @sid9890 Right now plugin supported only for the SSL connection and mapped jid.

I am expecting to make it usable for all of the options very shortly.

**Comment by gnusagit** [comment]
> @gnusagit @sid9890 Right now plugin supported only for the SSL connection and mapped jid.
> 
> I am expecting to make it usable for all of the options very shortly.

thank you for your answer. I hope this feature can be implemented soon. 
best regards.

**Comment by vavadiyahiren** [comment]
@gnusagit try with version1.1.15

**Comment by gnusagit** [comment]
Hello @vavadiyahiren 
thank you for your update the last few hours, it helped me a lot.

but I've try your example application from this git and still no luck. Is the change i have to do is just add a line of code below?

```
"requireSSLConnection": true,
"autoDeliveryReceipt": true,
```

or is there some other process i have to do? 
because, even though I'm using the new version of this plugin, it still has a information in my log like:

```
D/flutter_xmpp(12803):  Something went wrong while connecting ,make sure the credentials are right and try again: 
W/System.err(12803): org.jivesoftware.smack.SmackException$SecurityRequiredByServerException: SSL/TLS required by server but disabled in client
```
Thank you
