### ISSUE TITLE
Request MAM messages group chat

### ISSUE THREAD

**Issue by justiandevs** [vavadiyahiren/xmpp_plugin#41]
hey,

I've been integrating this flutter plugin into our flutter chat app for several days now. Now I have a question:

What's the common way within a group chat to fetch all posts on page load? I can't figure it out with the internet and I've tried everything (including requestMamMessages, which works for individual chats).

Unfortunately I'm missing some documentation and I really can't figure it out, can one of you help me?

Greetings,
justian

**Comment by samiulllah** [comment]
I'm trying to use xmpp with flutter using this plugin. I'm able to send message and get acks. But I'm unable to receive msgs from others. Have you faced this error?

**Comment by justiandevs** [comment]
> 

When you use following method:
`@override
  void onChatMessage(MessageChat messageChat) {
    events.add(messageChat);
    print('999999onChatMessage: ${messageChat.body}');
  }`

You are able to receive chatMessage events. After this you can choose what to do with them (parse them, send them to event handler etc)

**Comment by vavadiyahiren** [comment]
@justiandevs requestMamMessages should also work with the group chat, Can you check on the server side if the message history for the room is turned on ? 

Can you let me know the which xmpp server do you use and paste configuration file if possible.
