### ISSUE TITLE
message is not sent to the receiver

### ISSUE THREAD

**Issue by mkassir95** [vavadiyahiren/xmpp_plugin#48]
Hello,

I have this code 

>           int id = DateTime.now().millisecondsSinceEpoch;
          await xmppConnection.sendCustomMessage("mohammad@localhost","Hi","$id","customTest",DateTime.now().millisecondsSinceEpoch);

but the message is not sent to the receiver, I do not have new logs in the ejabberd docker image when I send a message 
![image](https://user-images.githubusercontent.com/72728047/206198703-a806c239-e717-41ba-a3ba-9b64368234f3.png)

**Comment by bazl-E** [comment]
@mkassir95 did you found any solutions
