### ISSUE TITLE
error when creating MUC

### ISSUE THREAD

**Issue by mkassir95** [vavadiyahiren/xmpp_plugin#51]
Hello,

I am trying to create an MUC using this code ` xmppConnection.createMUC("testRoom", true);`

I am getting this error 
`Error event {type: ErrorResponseState.group_creation_failed, from: testRoom, error: XMPP error reply received from conference.192.168.1.2: XMPPError: remote-server-not-found - cancel [DNS lookup failed: non-existing domain]}`

**Comment by vavadiyahiren** [comment]
@mkassir95 seems you are trying to connect in your local network, Can you check if firewall allows all port and ios devices are on the same network you are trying to connect with your server ?
