### ISSUE TITLE
not getting messages in listeners but getting in android logs

### ISSUE THREAD

**Issue by shyambandla** [vavadiyahiren/xmpp_plugin#52]
i'm trying to implement xmpp plugin. i can't see any xmppconnection.addListener . and I'm not getting messages into listers.

**Comment by shyambandla** [comment]
can anyone please give me the latest example

**Comment by vavadiyahiren** [comment]
Did you added listener well as explained in example ? @shyambandla 

Can you share the code snippet here to take a look ?

**Comment by Harshith996** [comment]
same issue

**Comment by sana2024** [comment]
for anyone ho wants to fix this, you have to add this line to your init 

  @override
  void initState() {
    XmppConnection.addListener(this);
    super.initState();
  }

then get back message in the event using log instead of print

**Comment by vavadiyahiren** [comment]
Listner even has been addressed in latest publish please check and reopen if it is still there.
