### ISSUE TITLE
sending a message to group of users

### ISSUE THREAD

**Issue by mkassir95** [vavadiyahiren/xmpp_plugin#55]
Hello,

I am trying to send a message to a group of users, but  I was not able to figure out how to do it .

I used this command  to create a chat room 
`xmppConnection.createMUC("testRoom@conference.localhost", true);`

And then I used to this command to join the group 
`await flutterXmpp.joinMucGroup("testRoom@conference.localhost"+"1");`

But the message was not sent to all members in the group, please guide me

**Comment by ismailgzn** [comment]
You should be a subscriber on muc group to send and get messages. 
Check the subscribers of group and than try again.

**Comment by mkassir95** [comment]
@ismailgzn 

hello, 

I am getting this error ` XMPPError: registration-required - auth [Membership is required to enter this room]`

**Comment by ismailgzn** [comment]
I was in same situtation on that work. And I could not be membership at group to join. And I solved the problem using ejabberd admin apis. Use subscribe api.
The link is https://docs.ejabberd.im/developer/ejabberd-api/admin-api

**Comment by vavadiyahiren** [comment]
@ismailgzn Thanks for your answer, @mkassir95 you need to be part of member-only group to join the MUC, You can do it with the ejabberd apis and try joining here.
