### ISSUE TITLE
getting an error when joining a group

### ISSUE THREAD

**Issue by mkassir95** [vavadiyahiren/xmpp_plugin#56]
Hello,

I am getting an error when joining a group 
`await flutterXmpp.joinMucGroup(xyz@conference.localhost)`

`joinGroup : exception: XMPP error reply received from train@conference.localhost/rawad: XMPPError: registration-required - auth [Membership is required to enter this room]`

**Comment by vavadiyahiren** [comment]
Looks like you are trying to join member-only room, Where first you need to add the member to that group and you can try to join that room again later, If still happens please re-open the issue.
