### ISSUE TITLE
Roadmap and documentation

### ISSUE THREAD

**Issue by ekremkmz** [vavadiyahiren/xmpp_plugin#7]
Hi sir! I have a few question and request about package.
Firstly, thanks for the package. Flutter really needed a package that uses native reliable libraries for XMPP.
Do you have a roadmap for features will gonna be added?
Specially, will you implement iq stanza listener? I'm using it for creating upload links and putting my files or images etc.
I'm trying to implement this package to my app that already uses a non-stable xmpp package.
Waiting for your response. Have a nice day.

**Comment by vavadiyahiren** [comment]
@ekremkmz 

Thanks for your support and feedbacks.

We are still looking to add basic things which is must needed to develop a core chat product and the next item is MAM (XEP-0313).

I agree on the lack of documentation part, That will be added as soon as i cover the feature part first.

I am planning to create a road map but as of now the short goal is to create a package which can help people to create a basic chat with the basic components like one-one chat, Group chat and MAM with presence and chat state notification.

I am about to design a roadmap very soon ! Cheers !!
