### ISSUE TITLE
Why does app crash on connection.start(onError) when you set 'minifyEnabled = true' for APK release, but when 'minifyEnabled = false' it works

### ISSUE THREAD

**Issue by isaanyoha** [vavadiyahiren/xmpp_plugin#71]
Why does app crash on connection.start(onError) when you set 'minifyEnabled = true' for APK release, but when 'minifyEnabled = false' it works. How do I fix this, please?

**Comment by SolinariWu** [comment]
You can look this https://github.com/vavadiyahiren/xmpp_plugin/issues/75 , I find the answer.

**Comment by isaanyoha** [comment]
Ok, Thank you!
