### ISSUE TITLE
List of muc rooms

### ISSUE THREAD

**Issue by iammuho** [vavadiyahiren/xmpp_plugin#73]
Hello,

I wonder if it's possible to list muc of the rooms + other conversations? Like whatsapp, so I want to list the users groups + conversations.

best regards

**Comment by therif** [comment]
yeah, please add listing group/muc where user already joined

**Comment by vavadiyahiren** [comment]
@iammuho @therif 

This plugin can't store the data so you need to create a offline database where you can fetch the roster by the plugin methods, Same with group as well, All the groups which you have joined need to store  with the custom database.
