### ISSUE TITLE
Calling login() will crash in Android release version

### ISSUE THREAD

**Issue by SolinariWu** [vavadiyahiren/xmpp_plugin#75]
I encountered the same problem as described in https://github.com/vavadiyahiren/xmpp_plugin/issues/37. Everything works fine in debug mode, able to login and send/receive messages. However, calling login() will crash in release version.

This issue occurs in xmpp_plugin 2.2.7 and also in the branch crashes_at_login_on_android, which was fixed in https://github.com/vavadiyahiren/xmpp_plugin/issues/37.

**Comment by SolinariWu** [comment]
I found the problem, it's because the proguard setting in Android release version was not configured correctly.

To set it up, go to the build.gradle file in the android/app directory of your Flutter project and add the following code to the buildTypes section:
```
buildTypes {
        release {
            minifyEnabled true
            shrinkResources true

            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
```
In addition, create a new file named proguard-rules.pro in the android/app directory, and add the following code to it:
```
-dontobfuscate
-keepattributes Signature
-keep class org.jivesoftware.smack.** { *; }
-keep class org.jivesoftware.smackx.** { *; }
```

**Comment by vavadiyahiren** [comment]
Yes @SolinariWu , this is correct finding.

You must need to apply proguard files for  ignoring smack libs.
