### ISSUE TITLE
Group chats

### ISSUE THREAD

**Issue by ismailgzn** [vavadiyahiren/xmpp_plugin#8]
Hi! 
First of all thank you for this work!
I have a questiıon about my project. 
When I install my app from playstore I need to get my group chats which is registered in the xmpp server.
I could not any idea about this in your package.
How can I do this?
Thank you very much again for your help!

**Comment by vavadiyahiren** [comment]
@ismailgzn thanks for the feedbacks.

i don't see any such XEP defined for that and nither i can find any support with exteral plugins, May be you can do that with the Rest apis offererd by different servers.
