### ISSUE TITLE
Doesn't get chatState event

### ISSUE THREAD

**Issue by housebackgammon** [vavadiyahiren/xmpp_plugin#88]
such an amazing client, thanks for the great work, 
however i have an issue with the onChatStateChange event, i use it to receive typing status but nothing is sent,

i run this code on one client:
await flutterXmpp.changeTypingStatus(userJid, typingStatus);

and i try to recieve it from another client with:
void onChatStateChange(ChatState chatState) {
  log("on chat state change ${chatState}")
}

but nothing is send inside the event, even tho i see it on the server logs and all of my other events work fine such as onNormalMessage or onPresenceChange

**Comment by housebackgammon** [comment]
this is my console log

![Screen Shot 2023-11-28 at 3 41 31 PM](https://github.com/vavadiyahiren/xmpp_plugin/assets/152283735/04f7cc4d-78db-48c3-b02f-becd611d640a)

where does these logs come from ?? and how can i access them and use the value inside it???

**Comment by dr7866** [comment]
W/MirrorManager(30303): this model don't Support
I/flutter (30303):  Plugin : User Jid : danish@chat.swatitech.com , Typing Status : typing 
D/flutter_xmpp(30303):  onMethodCall call: change_typing_status
D/flutter_xmpp(30303): userJId danish@chat.swatitech.com Typing Status : typing
W/System.err(30303): java.lang.IllegalArgumentException: No enum constant org.jivesoftware.smackx.chatstates.ChatState.typing
W/System.err(30303): 	at java.lang.Enum.valueOf(Enum.java:302)
W/System.err(30303): 	at org.jivesoftware.smackx.chatstates.ChatState.valueOf(ChatState.java:26)
W/System.err(30303): 	at org.xrstudio.xmpp.flutter_xmpp.Connection.FlutterXmppConnection.updateChatState(FlutterXmppConnection.java:428)
W/System.err(30303): 	at org.xrstudio.xmpp.flutter_xmpp.FlutterXmppPlugin.onMethodCall(FlutterXmppPlugin.java:699)
W/System.err(30303): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
W/System.err(30303): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
W/System.err(30303): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
W/System.err(30303): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
W/System.err(30303): 	at android.os.Handler.handleCallback(Handler.java:938)
W/System.err(30303): 	at android.os.Handler.dispatchMessage(Handler.java:99)
W/System.err(30303): 	at android.os.Looper.loopOnce(Looper.java:211)
W/System.err(30303): 	at android.os.Looper.loop(Looper.java:300)
W/System.err(30303): 	at android.app.ActivityThread.main(ActivityThread.java:8301)
W/System.err(30303): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(30303): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:577)
W/System.err(30303): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)


im facing this issue while calling xmppConnection?.changeTypingStatus("danish@chat.swatitech.com", status);

**Comment by dr7866** [comment]
@housebackgammon what are You sending in your typing status param

**Comment by vavadiyahiren** [comment]
@housebackgammon You can pass only chatstate string if you are passing some custom string it might not work as needed.

Ref Link for string value : https://download.igniterealtime.org/smack/docs/latest/javadoc/org/jivesoftware/smackx/chatstates/ChatState.html
