### ISSUE TITLE
crash on release Mode Apk

### ISSUE THREAD

**Issue by dr7866** [vavadiyahiren/xmpp_plugin#89]
basicalyy it works fine when i run the app in debug mode but when i run the app in release mode it give this log i'm using this version xmpp_plugin: 2.2.3 due to permission handler package
 
 FATAL EXCEPTION: Thread-9
E/AndroidRuntime(23150): Process: com.di.didconnect, PID: 23150
E/AndroidRuntime(23150): java.lang.ExceptionInInitializerError
E/AndroidRuntime(23150):        at rc.m.i(Unknown Source:0)
E/AndroidRuntime(23150):        at rc.d.<clinit>(Unknown Source:0)
E/AndroidRuntime(23150):        at nd.d.y(Unknown Source:0)
E/AndroidRuntime(23150):        at ye.a.f(Unknown Source:4)
E/AndroidRuntime(23150):        at org.xrstudio.xmpp.flutter_xmpp.Connection.FlutterXmppConnectionService.e(Unknown Source:36)
E/AndroidRuntime(23150):        at org.xrstudio.xmpp.flutter_xmpp.Connection.FlutterXmppConnectionService.b(Unknown Source:0)
E/AndroidRuntime(23150):        at org.xrstudio.xmpp.flutter_xmpp.Connection.FlutterXmppConnectionService$a.run(Unknown Source:15)
E/AndroidRuntime(23150):        at java.lang.Thread.run(Thread.java:1012)
E/AndroidRuntime(23150): Caused by: java.lang.IllegalStateException: Could not parse Smack configuration file
E/AndroidRuntime(23150):        at rc.p.<clinit>(Unknown Source:197)
E/AndroidRuntime(23150):        ... 8 more
E/AndroidRuntime(23150): Caused by: we.a: caused by: we.a: resource not found: /META-INF/services/org.xmlpull.v1.XmlPullParserFactory make sure that parser implementing 
XmlPull API is available
E/AndroidRuntime(23150):        at we.b.b(Unknown Source:214)
E/AndroidRuntime(23150):        at we.b.a(Unknown Source:1)
E/AndroidRuntime(23150):        at rc.p.d(Unknown Source:0)
E/AndroidRuntime(23150):        at rc.p.c(Unknown Source:6)
E/AndroidRuntime(23150):        at rc.p.<clinit>(Unknown Source:98)
E/AndroidRuntime(23150):        ... 8 more

**Comment by dr7866** [comment]
@florisgravendeel @vavadiyahiren @Kabariya @umairrafiq1133

**Comment by dr7866** [comment]
if possible please give updated packages support

**Comment by dr7866** [comment]
this is actually happens on your example Project 


adding listener: 
D/flutter_xmpp( 5227):  adding connection listener: 
D/flutter_xmpp( 5227):  adding success listener:
D/flutter_xmpp( 5227):  adding error listener:
D/flutter_xmpp( 5227):  onMethodCall call: login
D/flutter_xmpp( 5227):  onCreate():
D/flutter_xmpp( 5227):  onStartCommand():
D/flutter_xmpp( 5227):  Service Start() function called:
D/flutter_xmpp( 5227):  initConnection():
D/flutter_xmpp( 5227):  Connection Constructor called:
this is logs

**Comment by vavadiyahiren** [comment]
You might need to add proguard rules in production mode to prevent crash in release  mode.
