### ISSUE TITLE
Session expire issue 

### ISSUE THREAD

**Issue by dr7866** [vavadiyahiren/xmpp_plugin#93]
I'm encountering an issue where I've connected the same account to two devices. While the initial device successfully receives messages, the second device fails to do so. I aim to ensure that when I log in on the second device, the first device ceases to receive messages, and the most recent device takes over message reception responsibilities.

alternate when I login two accounts in same device listens of 1st account still alive and second account listeners are not listens to new messages even I logout the First account
@florisgravendeel @vavadiyahiren @therif @Kabariya @umairrafiq1133

**Comment by vavadiyahiren** [comment]
You need to make that configuration at the server level. Nothing to do at the frontend @dr7866

**Comment by dr7866** [comment]
@vavadiyahiren My connect() function is called but the issue is that very first time it print all connection logs but when i login another account without kill my app it will not print all the logs and not listen the new account messages
