### ISSUE TITLE
Message deliver and Seen Status 

### ISSUE THREAD

**Issue by dr7866** [vavadiyahiren/xmpp_plugin#99]
please tell me how I implement message seen or deliver status to sender  
@vavadiyahiren  any help ??
@umairrafiq1133

**Comment by vavadiyahiren** [comment]
@dr7866 You need to listen for delivery receipt and for seen message you need to send custom message with timestamp as soon message got displayed to the user, You can always send custom receipt to the other user.

**Comment by jeevan2304** [comment]
@danishrafiqe @vavadiyahiren ,
Did you get the delivery receipts ? for every outgoing message when the opposite user receives it?
I am not at all receiving the receipts and the delivery receipts is based on XEP - 0184 right???
